### ISSUE TITLE
About Voice Translation

### ISSUE THREAD

**Issue by degirmenciokann** [Jaykef/AvaChat#1]
Hello, I'm sorry I don't speak proper English.

I can access the API requested by the software into the system without any problems.

I want her to speak in Turkish, but what is the solution to answering one word in Turkish and the remaining words in English?,

Can you help on this issue?

Thank you very much.

enjoy your work.

**Comment by Jaykef** [comment]
For this you can add a Turkish voice id (e.g: tr-TR-EmelNeural) in the voiceUrlMap object in did-stream-api.js. I'm using microsoft voices you check more here: https://learn.microsoft.com/en-us/azure/ai-services/speech-service/language-support?tabs=tts

**Comment by Jaykef** [comment]
I'll close this issue now.
